version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      vue:
        patterns:
          - "@vue*"
          - "vue*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
