/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogPage: typeof import('./src/components/pages/BlogPage.vue')['default']
    BlogPostPreview: typeof import('./src/components/BlogPostPreview.vue')['default']
    EducationAndCertificationsSection: typeof import('./src/components/EducationAndCertificationsSection.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    LanguagesSection: typeof import('./src/components/LanguagesSection.vue')['default']
    LinkedInIcon: typeof import('./src/components/icons/LinkedInIcon.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NavigationBarRouterLink: typeof import('./src/components/NavigationBarRouterLink.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PortfolioPage: typeof import('./src/components/pages/PortfolioPage.vue')['default']
    PortfolioSingleElement: typeof import('./src/components/PortfolioSingleElement.vue')['default']
    ProfessionalExperienceSection: typeof import('./src/components/ProfessionalExperienceSection.vue')['default']
    ProfessionalSummarySection: typeof import('./src/components/ProfessionalSummarySection.vue')['default']
    ResumePage: typeof import('./src/components/pages/ResumePage.vue')['default']
    ResumeSingleElement: typeof import('./src/components/ResumeSingleElement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SectionSubheader: typeof import('./src/components/SectionSubheader.vue')['default']
    SocialIconsWrapper: typeof import('./src/components/SocialIconsWrapper.vue')['default']
    SocialLinksWrapper: typeof import('./src/components/SocialLinksWrapper.vue')['default']
    TagSocial: typeof import('./src/components/TagSocial.vue')['default']
    TagWithIcon: typeof import('./src/components/TagWithIcon.vue')['default']
    TechnicalSkillsSection: typeof import('./src/components/TechnicalSkillsSection.vue')['default']
  }
}
