/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/genAI-and-weapons-of-math-destruction': RouteRecordInfo<'/blog/genAI-and-weapons-of-math-destruction', '/blog/genAI-and-weapons-of-math-destruction', Record<never, never>, Record<never, never>>,
    '/blog/the-importance-of-test-driven-development': RouteRecordInfo<'/blog/the-importance-of-test-driven-development', '/blog/the-importance-of-test-driven-development', Record<never, never>, Record<never, never>>,
    '/portfolio': RouteRecordInfo<'/portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    '/resume': RouteRecordInfo<'/resume', '/resume', Record<never, never>, Record<never, never>>,
  }
}
