name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11'

      - name: Install dependencies
        run: npm install
  test:
    runs-on: ubuntu-latest
    needs: test

  deploy:
    runs-on: ubuntu-latest
    needs: setup && test
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gabcvit/gabcvit.github.io
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
