name: On Open Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  setup:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup.yml

  test:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/test.yml