name: On push to main
description: CI/CD pipeline that runs on push to main

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup.yml

  test:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy.yml