name: On push to main
description: CI/CD pipeline that runs on push to main

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    uses: ./.github/actions/dependency_setup

  test:
    runs-on: ubuntu-latest
    uses: ./.github/actions/run_tests

  deploy:
    runs-on: ubuntu-latest
    uses: ./.github/actions/build_deploy